### ISSUE TITLE
WebDAV client not working with D-Link DNS 320L

### ISSUE THREAD

**Issue by sylverb** [sylverb/NAStify#1]
When connecting to the WebDAV server running on a D-Link DNS 320L, Authentication seems to perform well, but when sending PROPFIND, the server returns "Permission denied".

**Comment by Neustradamus** [comment]
@sylverb: For information:

Note that D-Link DNS-320L and DNS-325 are supported in OpenWrt:
- https://github.com/openwrt/openwrt/pull/17924
- https://github.com/openwrt/openwrt/pull/16803
- https://github.com/openwrt/openwrt/pull/15433
