### ISSUE TITLE
Video stops/closes every few minutes (tvOS)

### ISSUE THREAD

**Issue by cbaltzer** [sylverb/NAStify#4]
I saw this issue was apparently fixed for SMB, but I'm still seeing it for OwnCloud. I haven't tested other sources. 

I don't see which commit would have fixed it for SMB, or I'd dig in and try to fix it myself. Though, I'm assuming it's the `stopPlayback` call in the player status change handler?

**Comment by sylverb** [comment]
This is strange, what kind of video file are you playing ?
It's normal that you don't find a commit for SMB/CIFS issues, I've done the corrections in libdsm library ( https://github.com/videolabs/libdsm/commits/master ) and these issues were only related to problems in this SMB/CIFS library !

Sylver

**Comment by cbaltzer** [comment]
I've only tried to play x264 MKVs so far. Not sure of the audio codecs in use, presumably AAC or AC3. I've seen this occur with files ranging from 200mb - 10gb, so I don't believe it's a throughput issue.
