### ISSUE TITLE
App Crash when upload/write file to shared folder With SMB through iOS App.

### ISSUE THREAD

**Issue by narendra-ct** [sylverb/NAStify#6]
Hi,

Thanks for the great lib, I'm trying to upload files with my iOS application and i have done some research on how to use smb_fwrite and finally I'm able to use it. But most of the times its crashing at

```
                    **__length = smb_fwrite(_uploadSession, _fileID, _buffer, _read_length);_**
```

please help me on this, how can i handle this?

Thanks in advance .

Narendra.

**Comment by sylverb** [comment]
Hi Narendra,
this is not the place to request help on how to use libdsm.
Anyway you can check my code to check how I use smb_fwrite : https://github.com/sylverb/NAStify/blob/master/NAStify/ConnectionManager/Plugins/Samba/CMSamba.m
